fix(faucet): update styles
haqq-network/frontend pull request #168
Opened 2023-06-08 14:19 UTC by hadzhehsen

2023-06-09 12:51 UTC, olegshilov requested changes

2023-06-09 12:51 UTC, olegshilov commented on apps/faucet/src/components/Faucet.tsx
> +        'font-serif text-[20px] font-[500] uppercase leading-[26px] text-white',
```suggestion
        'font-serif text-[20px] font-[500] leading-[26px] text-white',
```

2023-06-09 12:51 UTC, olegshilov commented on apps/faucet/src/components/AccountInfo.tsx
> +        <div className="flex h-[40px] flex-1 flex-row items-center justify-end gap-x-4 font-serif font-bold">
```suggestion
        <div className="flex h-[40px] flex-1 flex-row items-center justify-end gap-x-4 font-serif font-[500]">
```

2023-06-09 12:51 UTC, olegshilov commented on apps/faucet/tailwind.config.js
> +const typographyPlugin = require('@tailwindcss/typography');
no need to use this plugin in faucet app

2023-06-09 12:52 UTC, olegshilov requested changes

2023-06-09 12:52 UTC, olegshilov commented on apps/faucet/src/components/Faucet.tsx
> +                </span>
use `OrangeLink` component

2023-06-09 14:56 UTC, hadzhehsen commented on apps/faucet/tailwind.config.js
> +const typographyPlugin = require('@tailwindcss/typography');
Resolved

2023-06-09 14:56 UTC, hadzhehsen commented on apps/faucet/src/components/AccountInfo.tsx
> +        <div className="flex h-[40px] flex-1 flex-row items-center justify-end gap-x-4 font-serif font-bold">
Resolved

2023-06-09 14:56 UTC, hadzhehsen commented on apps/faucet/src/components/Faucet.tsx
> +        'font-serif text-[20px] font-[500] uppercase leading-[26px] text-white',
Resolved

2023-06-12 06:31 UTC, olegshilov requested changes

2023-06-12 06:31 UTC, olegshilov commented on apps/faucet/src/index.html
>        type="image/svg+xml"
`.ico` favicons must have different type

2023-06-12 07:25 UTC, hadzhehsen commented on apps/faucet/src/index.html
>        type="image/svg+xml"
Resolved

2023-06-12 07:43 UTC, olegshilov requested changes

2023-06-12 07:43 UTC, olegshilov commented on apps/faucet/src/index.html
> +  <meta name="description" content="HAQQ Faucet" />
```suggestion
  <meta name="description" content="HAQQ | Faucet" />
```

2023-06-12 07:43 UTC, olegshilov commented on apps/faucet/src/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
```suggestion
    <meta
      name="viewport"
      content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
```

2023-06-12 07:43 UTC, olegshilov commented on apps/faucet/src/index.html
> +  <link rel="icon" href="/icon.svg" type="image/svg+xml">
```suggestion
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
```

2023-06-12 07:53 UTC, hadzhehsen commented on apps/faucet/src/index.html
> +  <meta name="description" content="HAQQ Faucet" />
Resolved

2023-06-12 07:53 UTC, hadzhehsen commented on apps/faucet/src/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
Resolved

2023-06-12 13:01 UTC, olegshilov approved these changes

2023-06-12 14:23 UTC, merged