fix(vesting): new deposit withdrawal list item layout
haqq-network/frontend pull request #217
Opened 2023-07-07 12:13 UTC by hadzhehsen

2023-07-07 17:40 UTC, olegshilov approved these changes, later dismissed

2023-07-14 16:01 UTC, olegshilov requested changes

2023-07-14 16:01 UTC, olegshilov commented on apps/vesting/src/components/DepositWithdrawalList/DepositWithdrawalList.tsx
> +                fill="#2F2F2F"
```suggestion
                fill="currentColor"
```

2023-07-14 16:09 UTC, hadzhehsen commented on apps/vesting/src/components/DepositWithdrawalList/DepositWithdrawalList.tsx
> +                fill="#2F2F2F"
Resolved requested change

2023-07-14 16:31 UTC, olegshilov approved these changes

2023-07-14 16:32 UTC, merged