feat(islamic-coin-website): implement new islamic coin website
haqq-network/frontend pull request #253
Opened 2023-07-20 10:21 UTC by hadzhehsen

2023-07-25 10:43 UTC, ainfebrian commented
Faucet

2023-08-08 09:27 UTC, olegshilov requested changes

2023-08-08 09:27 UTC, olegshilov commented on libs/islamic-website/index-page/src/assets/images/mock_member.png
you have same image in app assets.

2023-08-08 12:34 UTC, olegshilov approved these changes

2023-08-08 12:35 UTC, merged