fix(islamic-website): metadata & metadata assets
haqq-network/frontend pull request #322
Opened 2023-08-21 12:29 UTC by hadzhehsen

2023-08-22 10:27 UTC, olegshilov requested changes

2023-08-22 10:27 UTC, olegshilov commented on apps/islamic-website/utils/get-news-data.ts
> +const VERCEL_ENV = process.env['VERCEL_ENV'];
lets move this vars to `constants.ts`

2023-08-22 10:27 UTC, olegshilov commented on apps/islamic-website/src/contansts.ts
move this file to project root

`apps/islamic-website/constants.tsx`

2023-08-22 10:39 UTC, hadzhehsen commented on apps/islamic-website/utils/get-news-data.ts
> +const VERCEL_ENV = process.env['VERCEL_ENV'];
Done

2023-08-22 10:39 UTC, hadzhehsen commented on apps/islamic-website/src/contansts.ts
Done

2023-08-22 13:30 UTC, olegshilov approved these changes, later dismissed

2023-08-24 19:33 UTC, olegshilov approved these changes

2023-08-24 19:43 UTC, merged