fix(islamic-website): requested fixes
haqq-network/frontend pull request #336
Opened 2023-08-28 16:33 UTC by hadzhehsen

2023-08-31 12:03 UTC, olegshilov requested changes

2023-08-31 12:03 UTC, olegshilov commented on apps/islamic-website/app/academy/page.tsx
> +    url: `${new URL(DEPLOY_URL)}academy`,
```suggestion
    url: `${new URL('/academy', DEPLOY_URL).toString()}`,
```

2023-08-31 13:55 UTC, hadzhehsen commented on apps/islamic-website/app/academy/page.tsx
> +    url: `${new URL(DEPLOY_URL)}academy`,
Done, in all pages

2023-08-31 14:42 UTC, olegshilov submitted a review, later dismissed

2023-08-31 14:42 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/new-member-card/new-member-card.tsx
> +            alt=""
```suggestion
            alt={title}
```

2023-08-31 14:45 UTC, olegshilov submitted a review, later dismissed

2023-09-01 10:35 UTC, olegshilov approved these changes

2023-09-01 10:41 UTC, merged