feat(islamic-website): add ar localization
haqq-network/frontend pull request #351
Opened 2023-09-08 15:16 UTC by hadzhehsen

2023-09-25 11:39 UTC, olegshilov requested changes

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/components/header/header.tsx
> +type localeType = 'en' | 'ar' | 'id';
```suggestion
type LocaleType = keyof typeof localeDisplayNames
```

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/components/header/header.tsx
> +                      locale={locale === 'ar' ? 'ar' : 'en'}
```suggestion
                      locale={locale}
```

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/components/header/header.tsx
> +                }
```suggestion
                title={localeDisplayNames[locale]}
```

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/components/layout/layout.tsx
> +  }, [shortLocale]);
why? just set `dir` html attribute below

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/components/layout/layout.tsx
> +  const shortLocale = locale ? locale : 'en';
why check this? locale is always string.

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/constants.tsx
> +];
remove from here and rename back to `constants.ts`

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/community-hub-page/src/assets/images/bg-image-ltr.svg
remove this. you can rotate image with css. just use `scale-x-[-1]` class

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/button/button.tsx
> +    'text-center uppercase text-[16px] leading-[1.5em] font-[400] font-mono rtl:font-handjet ',
```suggestion
    'text-center uppercase text-[16px] leading-[1.5em] font-[400] font-mono rtl:font-handjet',
```

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/download-pdf-button/download-pdf-button.tsx
> +            <span className="rtl:font-handjet font-mono  uppercase">
```suggestion
            <span className="rtl:font-handjet font-mono uppercase">
```

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/markdown-text/markdown-text.tsx
> +        'first:prose-td:pl-[16px] first:prose-td:pr-0 rtl:first:prose-td:pl-0 rtl:first:prose-td:pr-[16px]  even:prose-td:px-[24px] last:prose-td:pr-[16px] last:prose-td:pl-0 rtl:last:prose-td:pl-[16
```suggestion
        'first:prose-td:pl-[16px] first:prose-td:pr-0 rtl:first:prose-td:pl-0 rtl:first:prose-td:pr-[16px] even:prose-td:px-[24px] last:prose-td:pr-[16px] last:prose-td:pl-0 rtl:last:prose-td:pl-[16px] rtl:last:prose-td:pr-0',
```

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/member-card/member-card.tsx
> +                'text-islamic-primary-green hover:text-islamic-primary-green-hover rtl:font-handjet font-mono  uppercase',
remove double spaces everywhere

```suggestion
                'text-islamic-primary-green hover:text-islamic-primary-green-hover rtl:font-handjet font-mono uppercase',
```

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/member-modal-card/member-modal-card.tsx
> +            <div className="text-islamic-primary-green hover:text-islamic-primary-green-hover rtl:font-handjet mt-[8px] flex items-center gap-x-[4px] font-mono  uppercase transition-colors duration-3
```suggestion
            <div className="text-islamic-primary-green hover:text-islamic-primary-green-hover rtl:font-handjet mt-[8px] flex items-center gap-x-[4px] font-mono uppercase transition-colors duration-300 md:mt-[12px]">
```

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/news-card/news-card.tsx
> +              'mt-[24px] font-mono  text-[10px] font-[400] uppercase leading-[16px] text-[#838383] md:text-[11px] md:leading-[18px] lg:text-[12px]',
```suggestion
              'mt-[24px] font-mono text-[10px] font-[400] uppercase leading-[16px] text-[#838383] md:text-[11px] md:leading-[18px] lg:text-[12px]',
```

2023-09-25 11:39 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/news-card/news-card.tsx
> +            'mt-[16px] font-mono  text-[10px] uppercase leading-[16px] text-[#838383] md:text-[11px] md:leading-[18px] lg:text-[12px]',
revert

2023-09-25 11:39 UTC, olegshilov commented on apps/islamic-website/app/[locale]/privacy-policy/page.tsx
> +  const privacyPolicy = await getPrivacyPolicyContent(locale);
are you sure you get locale correctly?

2023-09-26 18:47 UTC, olegshilov commented
@hadzhehsen lets make envglish version first in language tab buttons
<img width="448" alt="image" src="https://github.com/haqq-network/frontend/assets/930121/0c61452a-1f73-4309-b414-ddff25100efc">

2023-09-26 18:48 UTC, olegshilov commented
@hadzhehsen this sticky menu should have blurred bg

<img width="392" alt="image" src="https://github.com/haqq-network/frontend/assets/930121/8f5a20a5-653e-4533-8966-97553826f363">

2023-09-26 18:48 UTC, olegshilov commented
translation for this

<img width="351" alt="image" src="https://github.com/haqq-network/frontend/assets/930121/6da3aaa3-2069-42fc-a959-498541ac6dd0">

2023-09-28 11:30 UTC, hadzhehsen commented on apps/islamic-website/constants.tsx
> +];
Done

2023-09-28 11:30 UTC, hadzhehsen commented on apps/islamic-website/components/layout/layout.tsx
> +  }, [shortLocale]);
Done

2023-09-28 11:30 UTC, hadzhehsen commented on libs/islamic-website/community-hub-page/src/assets/images/bg-image-ltr.svg
Done

2023-09-28 11:30 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/src/lib/button/button.tsx
> +    'text-center uppercase text-[16px] leading-[1.5em] font-[400] font-mono rtl:font-handjet ',
Done

2023-09-28 11:31 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/src/lib/download-pdf-button/download-pdf-button.tsx
> +            <span className="rtl:font-handjet font-mono  uppercase">
Done

2023-09-28 11:31 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/src/lib/markdown-text/markdown-text.tsx
> +        'first:prose-td:pl-[16px] first:prose-td:pr-0 rtl:first:prose-td:pl-0 rtl:first:prose-td:pr-[16px]  even:prose-td:px-[24px] last:prose-td:pr-[16px] last:prose-td:pl-0 rtl:last:prose-td:pl-[16
Done

2023-09-28 11:31 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/src/lib/member-modal-card/member-modal-card.tsx
> +            <div className="text-islamic-primary-green hover:text-islamic-primary-green-hover rtl:font-handjet mt-[8px] flex items-center gap-x-[4px] font-mono  uppercase transition-colors duration-3
Done

2023-09-28 11:32 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/src/lib/member-card/member-card.tsx
> +                'text-islamic-primary-green hover:text-islamic-primary-green-hover rtl:font-handjet font-mono  uppercase',
Done

2023-09-28 11:38 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/src/lib/news-card/news-card.tsx
> +              'mt-[24px] font-mono  text-[10px] font-[400] uppercase leading-[16px] text-[#838383] md:text-[11px] md:leading-[18px] lg:text-[12px]',
Done

2023-09-28 11:38 UTC, hadzhehsen commented on apps/islamic-website/app/[locale]/privacy-policy/page.tsx
> +  const privacyPolicy = await getPrivacyPolicyContent(locale);
Fixed

2023-10-02 08:59 UTC, olegshilov requested changes

2023-10-02 08:59 UTC, olegshilov commented on apps/islamic-website/app/[locale]/community-hub/page.tsx
> +import { SOCIAL_LINKS } from '../../../components/footer/social-links';
```suggestion
import { SOCIAL_LINKS } from '../../../social-links';
```

2023-10-02 08:59 UTC, olegshilov commented on apps/islamic-website/tailwind.config.js
> -        alexandria: ['var(--font-alexandria)'],
revert

2023-10-02 08:59 UTC, olegshilov commented on libs/islamic-website/shariah-page/src/lib/fatwa-block/fatwa-block.tsx
> +        ' rtl:font-handjet font-vcr cursor-pointer rounded-[8px] px-[12px] py-[8px]  text-[14px] font-[400] uppercase leading-[20px] text-white transition-colors duration-300',
```suggestion
        'rtl:font-handjet font-vcr cursor-pointer rounded-[8px] px-[12px] py-[8px]  text-[14px] font-[400] uppercase leading-[20px] text-white transition-colors duration-300',
```

2023-10-02 08:59 UTC, olegshilov commented on libs/islamic-website/ui-kit/.storybook/index.css
> -  --font-mono: 'VCR OSD Mono', var(--font-family-base);
revert

2023-10-02 08:59 UTC, olegshilov commented on libs/islamic-website/ui-kit/tailwind.config.js
> -        alexandria: ['var(--font-alexandria)'],
revert

2023-10-02 10:29 UTC, hadzhehsen commented on apps/islamic-website/tailwind.config.js
> -        alexandria: ['var(--font-alexandria)'],
Done

2023-10-02 10:29 UTC, hadzhehsen commented on libs/islamic-website/shariah-page/src/lib/fatwa-block/fatwa-block.tsx
> +        ' rtl:font-handjet font-vcr cursor-pointer rounded-[8px] px-[12px] py-[8px]  text-[14px] font-[400] uppercase leading-[20px] text-white transition-colors duration-300',
Done

2023-10-02 10:29 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/.storybook/index.css
> -  --font-mono: 'VCR OSD Mono', var(--font-family-base);
Done

2023-10-02 10:29 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/tailwind.config.js
> -        alexandria: ['var(--font-alexandria)'],
Done

2023-10-03 00:59 UTC, olegshilov requested changes

2023-10-03 00:59 UTC, olegshilov commented on libs/islamic-website/ui-kit/tailwind.config.js
> +        mono: ['var(--font-vcr)'],
```suggestion
        vcr: ['var(--font-vcr)'],
```

2023-10-03 00:59 UTC, olegshilov commented on apps/islamic-website/styles/consent-cookie.css
> +  @apply font-vcr uppercase;
rtl font

2023-10-04 11:39 UTC, hadzhehsen commented on apps/islamic-website/styles/consent-cookie.css
> +  @apply font-vcr uppercase;
Done

2023-10-04 11:39 UTC, hadzhehsen commented on libs/islamic-website/ui-kit/tailwind.config.js
> +        mono: ['var(--font-vcr)'],
Done

2023-10-06 08:47 UTC, olegshilov approved these changes, later dismissed

2023-10-06 09:23 UTC, olegshilov approved these changes

2023-10-06 09:51 UTC, merged