fix(islamic-website): move footer icons to public
haqq-network/frontend pull request #369
Opened 2023-09-16 15:45 UTC by hadzhehsen

2023-09-16 17:06 UTC, olegshilov requested changes

2023-09-16 17:06 UTC, olegshilov commented on apps/islamic-website/components/footer/footer.tsx
> +                  />
use css filter to make image grayscale

2023-09-16 17:39 UTC, hadzhehsen commented on apps/islamic-website/components/footer/footer.tsx
> +                  />
Done

2023-09-18 09:52 UTC, olegshilov submitted a review, later dismissed

2023-09-18 10:30 UTC, olegshilov approved these changes

2023-09-18 10:35 UTC, merged