fix(haqq-website): add label to subscribe form
haqq-network/frontend pull request #395
Opened 2023-09-26 23:12 UTC by hadzhehsen

2023-09-27 03:31 UTC, olegshilov requested changes

2023-09-27 03:31 UTC, olegshilov commented on libs/haqq-website/forms/src/lib/subscribe-form/subscribe-form.tsx
> +          >
this is not label
```suggestion
          <div className="mt-[4px] w-fit text-[12px] text-white">
```

2023-09-27 08:47 UTC, hadzhehsen commented on libs/haqq-website/forms/src/lib/subscribe-form/subscribe-form.tsx
> +          >
Done

2023-09-28 03:03 UTC, olegshilov approved these changes

2023-09-28 03:03 UTC, merged