fix(islamic-website): add label mobile markup
haqq-network/frontend pull request #396
Opened 2023-09-26 23:38 UTC by hadzhehsen

2023-09-27 03:30 UTC, olegshilov requested changes

2023-09-27 03:30 UTC, olegshilov commented on libs/islamic-website/forms/src/lib/subscribe-form/subscribe-form.tsx
> +          <label htmlFor="email" className="w-fit text-[12px] text-white">
this is not label.

```suggestion
          <div className="w-fit text-[12px] text-white">
```

2023-09-27 08:48 UTC, hadzhehsen commented on libs/islamic-website/forms/src/lib/subscribe-form/subscribe-form.tsx
> +          <label htmlFor="email" className="w-fit text-[12px] text-white">
Done

2023-09-28 03:03 UTC, olegshilov approved these changes

2023-09-28 03:03 UTC, merged