feat(islamic-website): disclaimer page, member card roles, team assets
haqq-network/frontend pull request #423
Opened 2023-10-05 15:06 UTC by hadzhehsen

2023-10-05 15:27 UTC, olegshilov requested changes

2023-10-05 15:27 UTC, olegshilov commented on libs/islamic-website/team-page/src/lib/team-page/team-page.tsx
> +const Team = [
```suggestion
const team = [
```

2023-10-05 15:27 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/member-card/member-card.tsx
> +
revert

2023-10-05 15:27 UTC, olegshilov commented on libs/islamic-website/ui-kit/src/lib/text/text.tsx
> +    isMono ? 'font-vcr uppercase' : 'font-alexandria',
rtl font

2023-10-05 15:31 UTC, olegshilov commented on libs/islamic-website/team-page/src/lib/team-page/team-page.tsx
> +const Team = [
and `Founders` => `founders`.
use first capital letter only for react compnents and classes

2023-10-05 15:32 UTC, olegshilov approved these changes, later dismissed

2023-10-06 03:12 UTC, kioqq approved these changes

2023-10-06 03:12 UTC, merged