chore(haqq-website): update wp asset
haqq-network/frontend pull request #478
Opened 2023-10-12 09:40 UTC by hadzhehsen

2023-10-12 10:49 UTC, olegshilov requested changes

2023-10-12 10:49 UTC, olegshilov commented on libs/haqq-website/whitepaper-page/src/lib/whitepaper-page.tsx
> +            href="/HAQQ-whitepaper.pdf"
revert

2023-10-12 15:01 UTC, hadzhehsen commented on libs/haqq-website/whitepaper-page/src/lib/whitepaper-page.tsx
> +            href="/HAQQ-whitepaper.pdf"
Done

2023-10-13 13:13 UTC, olegshilov approved these changes

2023-10-13 13:14 UTC, merged