feat(website): add wallet landing page
haqq-network/frontend pull request #54
Opened 2022-12-16 18:44 UTC by hadzhehsen

2022-12-16 22:18 UTC, olegshilov requested changes

2022-12-16 22:18 UTC, olegshilov commented on apps/website/pages/wallet.tsx
> +          <div className="flex justify-center">
```suggestion
          <div className="flex flex-1 justify-center">
```

2022-12-19 17:09 UTC, olegshilov requested changes

2022-12-19 17:09 UTC, olegshilov commented on apps/website/lib/fonts.ts
> +import { Manrope } from '@next/font/google';
```suggestion
import { El_Messiri, Manrope } from '@next/font/google';
```

2022-12-19 17:09 UTC, olegshilov commented on apps/website/pages/wallet.tsx
> +      <header className="header h-[70px] w-full py-[20px] sm:py-[22px]">
```suggestion
      <header className="h-[70px] w-full py-[20px] sm:py-[22px]">
```

2022-12-19 17:09 UTC, olegshilov commented on apps/website/pages/wallet.tsx
> +      <footer className="footer h-[96px] w-full">
```suggestion
      <footer className="h-[96px] w-full">
```

2022-12-19 18:03 UTC, hadzhehsen commented on apps/website/lib/fonts.ts
> +import { Manrope } from '@next/font/google';
Done

2022-12-19 18:03 UTC, hadzhehsen commented on apps/website/pages/wallet.tsx
> +      <header className="header h-[70px] w-full py-[20px] sm:py-[22px]">
Done

2022-12-19 18:03 UTC, hadzhehsen commented on apps/website/pages/wallet.tsx
> +      <footer className="footer h-[96px] w-full">
Done

2022-12-20 09:24 UTC, olegshilov requested changes

2022-12-20 09:24 UTC, olegshilov commented on libs/website/ui-kit/src/lib/icons/discord-icon.tsx
> +      fill="currentColor"
revert

2022-12-20 09:24 UTC, olegshilov commented on libs/website/ui-kit/src/lib/icons/link-arrow-icon.tsx
> +      fill="currentColor"
revert

2022-12-20 09:24 UTC, olegshilov commented on libs/website/ui-kit/src/lib/icons/medium-icon.tsx
> +      fill="currentColor"
revert

2022-12-20 09:24 UTC, olegshilov commented on libs/website/ui-kit/src/lib/icons/telegram-icon.tsx
> +      fill="currentColor"
revert

2022-12-20 09:24 UTC, olegshilov commented on libs/website/ui-kit/src/lib/icons/twitter-icon.tsx
> +      fill="currentColor"
revert

2022-12-20 09:24 UTC, olegshilov commented on libs/website/ui-kit/src/lib/icons/youtube-icon.tsx
> +      fill="currentColor"
revert

2022-12-20 11:05 UTC, hadzhehsen commented on libs/website/ui-kit/src/lib/icons/discord-icon.tsx
> +      fill="currentColor"
Done

2022-12-20 11:05 UTC, hadzhehsen commented on libs/website/ui-kit/src/lib/icons/link-arrow-icon.tsx
> +      fill="currentColor"
Done

2022-12-20 11:05 UTC, hadzhehsen commented on libs/website/ui-kit/src/lib/icons/telegram-icon.tsx
> +      fill="currentColor"
Done

2022-12-20 11:05 UTC, hadzhehsen commented on libs/website/ui-kit/src/lib/icons/youtube-icon.tsx
> +      fill="currentColor"
Done

2022-12-21 13:50 UTC, merged