feat(haqq-website): validators page
haqq-network/frontend pull request #574
Opened 2023-12-14 23:50 UTC by hadzhehsen

2023-12-16 07:42 UTC, olegshilov requested changes

2023-12-16 07:42 UTC, olegshilov commented on libs/haqq-website/ui-kit/src/lib/text/text.tsx
revert. text component should return span.

2023-12-16 18:32 UTC, hadzhehsen commented on libs/haqq-website/ui-kit/src/lib/text/text.tsx
Done

2023-12-18 10:34 UTC, olegshilov approved these changes

2023-12-18 10:35 UTC, merged