fix(islamic-website): prepare module 3 preview and lessons pages
haqq-network/frontend pull request #599
Opened 2023-12-22 13:20 UTC by hadzhehsen

2023-12-22 15:40 UTC, olegshilov requested changes

2023-12-22 15:40 UTC, olegshilov commented on libs/islamic-website/academy-page/src/lib/academy-preview-page/academy-preview-page.tsx
>      availableLessonsDate: new Date('2023-12-26'),
remove date from here.

2023-12-22 15:41 UTC, olegshilov commented
@hadzhehsen this request should contain changes next module

2023-12-26 01:38 UTC, hadzhehsen commented on libs/islamic-website/academy-page/src/lib/academy-preview-page/academy-preview-page.tsx
>      availableLessonsDate: new Date('2023-12-26'),
Done

2023-12-26 08:19 UTC, olegshilov approved these changes

2023-12-26 08:19 UTC, merged