fix(islamic-website): add missing dexs cards
haqq-network/frontend pull request #775
Opened 2024-04-16 12:25 UTC by hadzhehsen

2024-04-16 16:07 UTC, olegshilov requested changes

2024-04-16 16:07 UTC, olegshilov commented on libs/islamic-website/markets-page/src/lib/markets-page/markets-page.tsx
> +      },
```suggestion
      {
        pair: ['USDC.axl', 'ISLM'],
        href: 'https://app.osmosis.zone/?to=ISLM&from=USDC.axl',
      },
      {
        pair: ['WBTC.axl', 'ISLM'],
        href: 'https://app.osmosis.zone/?to=ISLM&from=WBTC.axl',
      },
```

2024-04-16 16:32 UTC, hadzhehsen commented on libs/islamic-website/markets-page/src/lib/markets-page/markets-page.tsx
> +      },
Done

2024-04-17 08:49 UTC, olegshilov approved these changes

2024-04-17 08:49 UTC, merged