feat(islamic-website): add download qr button to main & wallet pages
haqq-network/frontend pull request #793
Opened 2024-04-25 15:42 UTC by hadzhehsen

2024-04-25 16:54 UTC, kioqq approved these changes, later dismissed
LGTM

2024-04-26 07:54 UTC, olegshilov approved these changes

2024-04-26 07:55 UTC, olegshilov requested changes

2024-04-26 07:55 UTC, olegshilov commented on libs/islamic-website/index-page/src/lib/portfolio-block/portfolio-block.tsx
> +      return {};
Why?

2024-04-26 08:13 UTC, olegshilov approved these changes, later dismissed

2024-04-26 09:21 UTC, olegshilov approved these changes

2024-04-26 09:45 UTC, merged