fix(staking): add sort numbers
haqq-network/frontend pull request #894
Opened 2024-07-19 11:30 UTC by hadzhehsen

closes: WEB-309

2024-07-21 09:00 UTC, olegshilov requested changes

2024-07-21 09:00 UTC, olegshilov commented on libs/staking/src/lib/components/validator-list-item-desktop.tsx
> +  sortState: SortState;
```suggestion
  index?: number;
```

2024-07-21 09:00 UTC, olegshilov commented on libs/staking/src/lib/components/validator-list-desktop.tsx
> +              sortState={sortState}
```suggestion
              index={sortState !== 'random' ? index + 1 : undefined}
```

2024-07-21 09:00 UTC, olegshilov commented on libs/staking/src/lib/components/validator-list-desktop.tsx
> +              <div className="select-none">#</div>
```suggestion
              <div className="select-none">&nbsp;</div>
```

2024-07-22 11:44 UTC, hadzhehsen commented on libs/staking/src/lib/components/validator-list-item-desktop.tsx
> +  sortState: SortState;
Done

2024-07-22 11:44 UTC, hadzhehsen commented on libs/staking/src/lib/components/validator-list-desktop.tsx
> +              sortState={sortState}
Done

2024-07-22 11:44 UTC, hadzhehsen commented on libs/staking/src/lib/components/validator-list-desktop.tsx
> +              <div className="select-none">#</div>
Done

2024-07-26 08:28 UTC, olegshilov submitted a review, later dismissed

2024-07-26 08:38 UTC, olegshilov approved these changes

2024-07-26 09:26 UTC, merged